### ISSUE TITLE
Custom The-Culture Plugin in Repo

### ISSUE THREAD

**Issue by mglinski** [sovereignbot/citadel#11]
Not sure you wanted this in the repo: https://github.com/karbowiak/Sovereign/blob/master/src/plugins/onTimer/jabberPingsTheCulture.php

**Comment by karbowiak** [comment]
For now it's fine - i have yet to come up with a way to split this out into it's own plugin, that can be configured per. server.

I guess that'll come when i eventually write the webpanel for it... but who knows when that'll happen :D

**Comment by mglinski** [comment]
Make the plugins you can install configurable in the config file, then you can just have a private composer package to add sensitive plugins and configure them per install.

**Comment by karbowiak** [comment]
You can enable/disable plugins in the main executable, just comment the line.

I considered moving it to the config, but then decided i wasn't really gonna make it so others could use it as such, since not many would want to compile a full php7 zts install with pthreads.

You're actually the first one brave enough to attempt it, haha :D

**Comment by mglinski** [comment]
It's easy enough to do in ubuntu, there is a PPA for php7 with zts enabled, so getting everything working took about 20 mins. Just have to install and load pthreads and it was good to go.

I think most big users of this are gonna want to run their own installs once the process is documented. Discord bots can do very meta things with eve based chat logs that it can see :)

Ill see about adding a config extendable plugin listing.
